// SPDX-License-Identifier: GPL-3.0-only
import {
    StandardButton,
    VerticalBox,
    Button,
    HorizontalBox,
} from "std-widgets.slint";

export component GetAge inherits Window {

    callback quit();
    callback open_url(url: string);

    VerticalBox {
        Text {
            text: "Please install either AGE or RAGE!";
            vertical-stretch: 1;
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        HorizontalBox {
            Button {
                text: "Get AGE";
                clicked => open_url("https://github.com/FiloSottile/age");
            }

            Button {
                text: "Get RAGE";
                clicked => open_url("https://github.com/str4d/rage");
            }

            StandardButton {
                kind: close;
                clicked => quit();
            }
        }
    }
}
